lang: RU

#msgs here are deprecated, use Translations/your lang (which is "lang" value in config) to edit msgs / сообщения тут устарели, используйте папку translations/язык который указан выше!
messages: #RU msgs btw
  help:
    - "&6======================="
    -  ""
    -  "&fПомощь по командам"
    -    "&6  /heal - захилить себя или другого игрока"
    -    "&6  /feed - накормить себя или другого игрока"
    -    "&6  /spawn - телепорт на спавн"
    -    "&6  /tpa <игрок> - запрос на телепорт"
    -    "&6  /tpaccept - принять запрос на телепорт"
    -    "&6  /tpdeny - отклонить запрос на телепорт"
    -  ""
    -  "&6======================="
  noPermission: '&c[✘] &fНет, &cты не можешь использовать&f эту команду.'
  playerNotFound: '&c[✘] &fИгрок не найден.'
  invalidMode: '&c[✘] &fТакого режима &cне существует.'
  usage: '&c[✘] &fнеправильная команда, используйте: %s'
  spawnSet: '&6[✔] &fСпавн успешно &6установлен'
  spawnTeleportSuccess: '&6[✔] &fТелепортация на &6спавн...'
  configReloaded: '&6[✔]  &fКонфигурация CatAPI перезагружена, спасибо что используешь мой плагин.'
  NoOneAtNear: "&c[✘] &6радар > &fвокруг вас никого нет"
  repairSuccessAll: '&6[✔] починка > вы починили все предметы!'
  repairSuccessHand: '&6[✔] починка > вы починили успешно предмет в вашей руке'
  repairNotSuccess: '&c[✘] починка > вы не можете починить этот предмет'
  InvalidRadius: "&c[✘] &6радар > &fНе верный радиус используйте от 1 до 100"
  nearPlayers: '&6[✔] &6радар > &fокружающие игроки в радиусе {radius}: {players}'
  CannotUseRadius: '&6[✔] &6радар > &fвы не можете использовать этот радиус'
  ElytraRequired: '&c[✘] &fу вас нету элитр, наденьте их и пропишите команду снова'
  tpaSent: '&6[Ⓘ] &fЗапрос на телепортацию отправлен игроку &e%player%&f!'
  tpaReceived: '&6[Ⓘ] &eИгрок &f%player% &eхочет к вам телепортироваться!'
  tpSuccess: '&6[✔] &fВы успешно телепортировались к игроку &e%s&f!'
  noPendingRequests: '&c[✘] &fУ вас нет ожидающих запросов на телепортацию!'
  tpaSenderOffline: '&c[✘] &fОтправитель больше не в сети!'
  tpaDenied: '&c[✘] &fИгрок &e%player% &f отклонил ваш запрос на телепортацию!'
  tpaRejected: '&eВы отклонили запрос на телепортацию от &e%player%&f.'
  specSuccess: '&6[✔] &fВы начали следить за &e%s&a.'
  gmSuccess: '&6[✔] &fВы переключились в режим &e%s&a.'
  godToggled: '&6[✔] &fВаш режим бога %s.'
  flyToggled: '&6[✔] &fВаш режим полета %s.'
  healSuccess: '&6[❤] &fВы были исцелены.'
  feedSuccess: '&6[☕] &fВы поели'
  healTargeted: '&6[❤] &fВы вылечили игрока &6&f%s'
  feedTargeted: '&6[☕] &fВы покормили игрока &6&f%s'
  godToggleSuccess: '&6[✔] &fВы изменили режим бога для &e%s&a.'
  flyToggleSuccess: '&6[✔]&fВы изменили режим полета для &e%s&a.'
  godModeItemPickupDenied: '&c[✘] &fВы не можете подбирать предметы в режиме бога.'
  tphereToYouSuccess: "&6[Ⓘ] &fВас телепортировал к себе &e%s&a"
  tphereSuccess: "&6[✔] &fИгрок успешно телепортирован к вам &e%s&a"
  itemNoItemInHand: '&c[✘] &fУ вас нет предмета в руке!'
  itemSetNameSuccess: '&6[✔] &fНазвание предмета успешно установлено: &e%s'
  itemSetLoreSuccess: '&6[✔] &fОписание предмета успешно установлено.'
  itemEnchantSuccess: '&6[✔] &fПредмет успешно зачарован: &e%s &fуровень &e%d'
  itemInvalidEnchantment: '&c[✘] &fНеизвестное зачарование: &e%s'
  itemLevelMustBeNumber: '&c[✘] &fУровень должен быть числом!'
  itemUsageSetName: '&c[✘] &fИспользование: &e/setname <название>'
  itemUsageSetLore: '&c[✘] &fИспользование: &e/setlore <текст описания>'
  itemUsageEnchant: '&c[✘] &fИспользование: &e/enchant <зачарование> <уровень>'
  vanishEnabled: '&6[✔] &fВы вошли в &6ваниш&f. Вы невидимы для других игроков.'
  vanishDisabled: '&c[✘] &fВы вышли из &6ваниша&f.'
  noPermissionVanish: '&c[✘] &fУ вас нет прав для использования этой команды.'
  vanishBossBarTitle: '&6Режим невидимости'
  gameModeMessages:
    SURVIVAL: '&a[✔] &fВы переключились в режим &6сурвайвал.'
    CREATIVE: '&a[✔] &fВы переключились в режим &6креатив.'
    ADVENTURE: '&a[✔] &fВы переключились в режим &6адвенчер.'
    SPECTATOR: '&a[✔] &fВы переключились в режим &6спектатор.'
#here comes not deprecated part



  tpa:
    teleport-delay: 10
  bossbars:
    bossBarTPToSpawn:
      title: '&6Телепортация через: &c{seconds} сек'
      color: 'YELLOW'
      style: 'SOLID'
spawn:
  world: spawn
  x: 0.4477384777701915
  y: 93.0
  z: 0.6335880333127843
  yaw: -359.1185
  pitch: 3.227538
#not realized
  arenas:
    death:
      region:
        name: "pvpcmert"
        Arena-location:
          world: "spawn"
          x: -236
          y: 82
          z: 219


      msgs: # сообщения
        notInRegion: "&c[✘] &fВы &cне находитесь на арене."
        created: '&a[✔] &fАрена &6%s &fуспешно создана!'
        alreadyExists: '&c[✘] &fАрена с таким именем уже существует.'
        notFound: '&c[✘] &fНет такой арены.'
        entered: '&a[✔] &fВы вошли на арену &6%s&a.'
        left: '&a[✔] &fВы покинули арену.'
        NoRequire: '&c[✘] &fУ вас нет &6необходимой &fэкипировки'
        cannotUseCmdAtRegion: '&c[✘] &fвы &cне &fможете использовать команды на арене смерти!'

      cmd-whiteList:
        - arena # команда для того, чтобы уйти на спавн с арены (/arena leave) (уйти можно только через команду)
      spawn:
        world: "spawn"
        x: 0.4477384777701915
        y: 93.0
        z: 0.6335880333127843
      require-items:
        - NETHERITE_SWORD
        - NETHERITE_HELMET
        - NETHERITE_CHESTPLATE
        - NETHERITE_BOOTS
        - NETHERITE_LEGGINS
      bossbars:
        bossBarTPToSpawn:
          title: "&6Teleporting in: &c{seconds} сек"
          color: "YELLOW"
          style: "SOLID"

        pvpMode:
          title: "&c&lPVP &f&l- &aACTIVE"
          color: "RED"
          style: "SOLID"

