lang: RU

spawn:
  world: spawn
  x: 0.4477384777701915
  y: 93.0
  z: 0.6335880333127843
  yaw: -359.1185
  pitch: 3.227538
#not realized
  arenas:
    death:
      region:
        name: "pvpcmert"
        Arena-location:
          world: "spawn"
          x: -236
          y: 82
          z: 219


      msgs: # сообщения
        notInRegion: "&c[✘] &fВы &cне находитесь на арене."
        created: '&a[✔] &fАрена &6%s &fуспешно создана!'
        alreadyExists: '&c[✘] &fАрена с таким именем уже существует.'
        notFound: '&c[✘] &fНет такой арены.'
        entered: '&a[✔] &fВы вошли на арену &6%s&a.'
        left: '&a[✔] &fВы покинули арену.'
        NoRequire: '&c[✘] &fУ вас нет &6необходимой &fэкипировки'
        cannotUseCmdAtRegion: '&c[✘] &fвы &cне &fможете использовать команды на арене смерти!'

      cmd-whiteList:
        - arena
      spawn:
        world: "spawn"
        x: 0.4477384777701915
        y: 93.0
        z: 0.6335880333127843
      require-items:
        - NETHERITE_SWORD
        - NETHERITE_HELMET
        - NETHERITE_CHESTPLATE
        - NETHERITE_BOOTS
        - NETHERITE_LEGGINS
      bossbars:
        bossBarTPToSpawn:
          title: "&6Teleporting in: &c{seconds} сек"
          color: "YELLOW"
          style: "SOLID"

        pvpMode:
          title: "&c&lPVP &f&l- &aACTIVE"
          color: "RED"
          style: "SOLID"

